version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - lucacasonato
  ignore:
  - dependency-name: github.com/eclipse/paho.mqtt.golang
    versions:
    - 1.3.1
    - 1.3.2
